"""Localized bot interface strings (buttons, prompts, system messages).
Story narration itself is generated by Gemini in the chosen language
separately — these are the fixed strings the bot code sends directly."""

STRINGS: dict[str, dict[str, str]] = {
    "uk": {
        "start": (
            "Вітаю у текстовій DnD-пригоді!\n\n"
            "Команди:\n"
            "/new — почати нову пригоду (мова, світ, персонаж)\n"
            "/roll — кинути кубик d20 вручну (тестовий, без прив'язки до гри)\n"
            "/reset — стерти прогрес і почати з нуля\n\n"
            "Після створення пригоди просто пиши дії текстом або тисни кнопки."
        ),
        "choose_category": "Обери категорію світу для пригоди:",
        "describe_world": (
            "Опиши своїми словами світ, де відбуватиметься історія (кілька речень),\n"
            "або натисни кнопку, щоб я вигадав світ сам:"
        ),
        "world_random_button": "🎲 Хай світ вигадає AI",
        "world_random_ack": "Гаразд, вигадаю світ сам",
        "character_method_prompt": "Як створимо персонажа?",
        "character_manual_button": "✍️ Опишу персонажа сам",
        "character_random_button": "🎲 Згенерувати випадково",
        "describe_character_prompt": (
            "Опиши персонажа: ім'я, стать, вік, клас/професія, коротка передісторія — "
            "що вважаєш за потрібне:"
        ),
        "choose_gender": "Обери стать персонажа:",
        "gender_male": "Чоловіча",
        "gender_female": "Жіноча",
        "gender_any": "Будь-яка",
        "enter_age_prompt": "Вкажи вік персонажа числом (наприклад, 27), або напиши 'будь-який':",
        "creating": "Створюю світ і персонажа, зачекай кілька секунд...",
        "gemini_error": "Помилка звернення до Gemini: {error}",
        "no_active_game": "Спочатку почни пригоду командою /new",
        "hp_label": "❤️ HP",
        "defeated": "💀 Персонаж втратив свідомість. Напиши /new, щоб почати заново.",
        "reset_done": "Прогрес стерто. Напиши /new, щоб почати заново.",
        "please_wait": "⏳ Попередній хід ще обробляється, зачекай секунду...",
        "dice_roll_label": "🎲 Кидок d{sides}",
        "dice_penalty_note": " (штраф {penalty} через поранення)",
        "dice_total": "Підсумок: {total}",
        "choosing_option": "Обираю варіант {n}",
        "rolled_action": "Кидаю кубик d{sides}: випало {value}{penalty_note}.",
        "requires_roll_hint": "(потрібен кидок d20)",
        "tier_critical_failure": "Фатальна невдача",
        "tier_failure": "Невдача",
        "tier_partial_success": "Частковий успіх",
        "tier_success": "Успіх",
        "tier_critical_success": "Критичний успіх",
        "preview_regen_button": "🔄 Згенерувати ще раз",
        "preview_accept_button": "✅ Підходить, далі",
        "generating_preview": "Генерую варіант...",
        "open_miniapp_button": "🎮 Відкрити пригоду",
        "play_intro": "Тисни кнопку, щоб відкрити гру як застосунок:",
    },
    "en": {
        "start": (
            "Welcome to the text-based DnD adventure!\n\n"
            "Commands:\n"
            "/new — start a new adventure (language, world, character)\n"
            "/roll — roll a d20 manually (test only, not tied to the game)\n"
            "/reset — wipe progress and start over\n\n"
            "Once the adventure begins, just type your actions or tap the buttons."
        ),
        "choose_category": "Choose a world category for the adventure:",
        "describe_world": (
            "Describe in your own words the world this story takes place in (a few sentences),\n"
            "or tap the button to let the AI invent one:"
        ),
        "world_random_button": "🎲 Let AI invent the world",
        "world_random_ack": "Alright, I'll invent the world myself",
        "character_method_prompt": "How should we create the character?",
        "character_manual_button": "✍️ I'll describe them myself",
        "character_random_button": "🎲 Generate randomly",
        "describe_character_prompt": (
            "Describe the character: name, gender, age, class/profession, a short backstory — "
            "whatever you think matters:"
        ),
        "choose_gender": "Choose the character's gender:",
        "gender_male": "Male",
        "gender_female": "Female",
        "gender_any": "Any",
        "enter_age_prompt": "Enter the character's age as a number (e.g. 27), or type 'any':",
        "creating": "Creating the world and character, give me a few seconds...",
        "gemini_error": "Error contacting Gemini: {error}",
        "no_active_game": "Start an adventure first with /new",
        "hp_label": "❤️ HP",
        "defeated": "💀 The character has fallen unconscious. Type /new to start over.",
        "reset_done": "Progress wiped. Type /new to start over.",
        "please_wait": "⏳ Still processing the previous turn, hang on a second...",
        "dice_roll_label": "🎲 d{sides} roll",
        "dice_penalty_note": " (penalty {penalty} from injuries)",
        "dice_total": "Total: {total}",
        "choosing_option": "Choosing option {n}",
        "rolled_action": "Rolling a d{sides}: got {value}{penalty_note}.",
        "requires_roll_hint": "(requires a d20 roll)",
        "tier_critical_failure": "Critical failure",
        "tier_failure": "Failure",
        "tier_partial_success": "Partial success",
        "tier_success": "Success",
        "tier_critical_success": "Critical success",
        "preview_regen_button": "🔄 Generate another",
        "preview_accept_button": "✅ Works for me, continue",
        "generating_preview": "Generating an option...",
        "open_miniapp_button": "🎮 Open adventure",
        "play_intro": "Tap the button to open the game as an app:",
    },
    "ru": {
        "start": (
            "Добро пожаловать в текстовое DnD-приключение!\n\n"
            "Команды:\n"
            "/new — начать новое приключение (язык, мир, персонаж)\n"
            "/roll — бросить кубик d20 вручную (тестовый, не привязан к игре)\n"
            "/reset — стереть прогресс и начать заново\n\n"
            "После создания приключения просто пиши действия текстом или жми кнопки."
        ),
        "choose_category": "Выбери категорию мира для приключения:",
        "describe_world": (
            "Опиши своими словами мир, где будет происходить история (несколько предложений),\n"
            "или нажми кнопку, чтобы я придумал мир сам:"
        ),
        "world_random_button": "🎲 Пусть AI придумает мир",
        "world_random_ack": "Хорошо, придумаю мир сам",
        "character_method_prompt": "Как создадим персонажа?",
        "character_manual_button": "✍️ Опишу персонажа сам",
        "character_random_button": "🎲 Сгенерировать случайно",
        "describe_character_prompt": (
            "Опиши персонажа: имя, пол, возраст, класс/профессия, короткая предыстория — "
            "что считаешь важным:"
        ),
        "choose_gender": "Выбери пол персонажа:",
        "gender_male": "Мужской",
        "gender_female": "Женский",
        "gender_any": "Любой",
        "enter_age_prompt": "Укажи возраст персонажа числом (например, 27), или напиши 'любой':",
        "creating": "Создаю мир и персонажа, подожди пару секунд...",
        "gemini_error": "Ошибка обращения к Gemini: {error}",
        "no_active_game": "Сначала начни приключение командой /new",
        "hp_label": "❤️ HP",
        "defeated": "💀 Персонаж потерял сознание. Напиши /new, чтобы начать заново.",
        "reset_done": "Прогресс стёрт. Напиши /new, чтобы начать заново.",
        "please_wait": "⏳ Предыдущий ход ещё обрабатывается, подожди секунду...",
        "dice_roll_label": "🎲 Бросок d{sides}",
        "dice_penalty_note": " (штраф {penalty} из-за ранения)",
        "dice_total": "Итог: {total}",
        "choosing_option": "Выбираю вариант {n}",
        "rolled_action": "Бросаю кубик d{sides}: выпало {value}{penalty_note}.",
        "requires_roll_hint": "(нужен бросок d20)",
        "tier_critical_failure": "Фатальная неудача",
        "tier_failure": "Неудача",
        "tier_partial_success": "Частичный успех",
        "tier_success": "Успех",
        "tier_critical_success": "Критический успех",
        "preview_regen_button": "🔄 Сгенерировать ещё раз",
        "preview_accept_button": "✅ Подходит, далее",
        "generating_preview": "Генерирую вариант...",
        "open_miniapp_button": "🎮 Открыть приключение",
        "play_intro": "Нажми кнопку, чтобы открыть игру как приложение:",
    },
    "pl": {
        "start": (
            "Witaj w tekstowej przygodzie DnD!\n\n"
            "Komendy:\n"
            "/new — rozpocznij nową przygodę (język, świat, postać)\n"
            "/roll — rzuć kością d20 ręcznie (testowe, niepowiązane z grą)\n"
            "/reset — wyczyść postępy i zacznij od nowa\n\n"
            "Po stworzeniu przygody po prostu wpisuj działania lub klikaj przyciski."
        ),
        "choose_category": "Wybierz kategorię świata dla przygody:",
        "describe_world": (
            "Opisz własnymi słowami świat, w którym rozgrywa się historia (kilka zdań),\n"
            "albo kliknij przycisk, żeby AI wymyśliło świat samo:"
        ),
        "world_random_button": "🎲 Niech AI wymyśli świat",
        "world_random_ack": "Dobrze, sam wymyślę świat",
        "character_method_prompt": "Jak stworzymy postać?",
        "character_manual_button": "✍️ Opiszę postać sam",
        "character_random_button": "🎲 Wygeneruj losowo",
        "describe_character_prompt": (
            "Opisz postać: imię, płeć, wiek, klasa/zawód, krótka historia — "
            "co uważasz za ważne:"
        ),
        "choose_gender": "Wybierz płeć postaci:",
        "gender_male": "Męska",
        "gender_female": "Żeńska",
        "gender_any": "Dowolna",
        "enter_age_prompt": "Podaj wiek postaci liczbą (np. 27), albo napisz 'dowolny':",
        "creating": "Tworzę świat i postać, daj mi kilka sekund...",
        "gemini_error": "Błąd połączenia z Gemini: {error}",
        "no_active_game": "Najpierw rozpocznij przygodę komendą /new",
        "hp_label": "❤️ HP",
        "defeated": "💀 Postać straciła przytomność. Wpisz /new, żeby zacząć od nowa.",
        "reset_done": "Postępy wyczyszczone. Wpisz /new, żeby zacząć od nowa.",
        "please_wait": "⏳ Poprzednia tura wciąż się przetwarza, poczekaj chwilę...",
        "dice_roll_label": "🎲 Rzut d{sides}",
        "dice_penalty_note": " (kara {penalty} za obrażenia)",
        "dice_total": "Wynik: {total}",
        "choosing_option": "Wybieram opcję {n}",
        "rolled_action": "Rzucam kością d{sides}: wypadło {value}{penalty_note}.",
        "requires_roll_hint": "(wymaga rzutu d20)",
        "tier_critical_failure": "Krytyczna porażka",
        "tier_failure": "Porażka",
        "tier_partial_success": "Częściowy sukces",
        "tier_success": "Sukces",
        "tier_critical_success": "Krytyczny sukces",
        "preview_regen_button": "🔄 Wygeneruj ponownie",
        "preview_accept_button": "✅ Pasuje, dalej",
        "generating_preview": "Generuję propozycję...",
        "open_miniapp_button": "🎮 Otwórz przygodę",
        "play_intro": "Kliknij przycisk, aby otworzyć grę jako aplikację:",
    },
}

DEFAULT_UI_LANG = "uk"


def t(lang_key: str, string_key: str, **kwargs) -> str:
    lang = STRINGS.get(lang_key, STRINGS[DEFAULT_UI_LANG])
    template = lang.get(string_key) or STRINGS[DEFAULT_UI_LANG].get(string_key, string_key)
    return template.format(**kwargs) if kwargs else template
